[build-system]
requires = [
    "scikit-build-core>=0.10", 
    "pybind11>=2.12"
]
build-backend="scikit_build_core.build"

[tool.scikit-build]
cmake.source-dir = "cpp"
wheel.packages = [
    "visual_memory"
]

[project]
name="ChronoVision"
version="0.1"
dependencies = [
    "dotenv>=0.9.9",
    "psycopg>=3.3.6",
    "pybind11>=3.1.0",
    "pydantic>=2.13.5",
    "scikit-build-core>=1.1.0",
    "sqlalchemy>=2.1.1",
    "ultralytics>=8.4.163",
]
